---

- name: create directory for cert releated files
  file: path=/etc/pki/etcd/private state=directory mode=755

- name: copy cert file to flannel
  copy: src={{ flannel_cert_file_path }} dest=/etc/pki/etcd/etcd.crt

- name: copy key file to flannel
  copy: src={{ flannel_key_file_path }} dest=/etc/pki/etcd/private/etcd.key

- name: copy cacert file to flannel
  copy: src={{ flannel_cacert_file_path }} dest=/etc/pki/etcd/cacert.pem

